routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Noticia;
use App\Http\Controllers\NoticiaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('noticias',NoticiaController::class);
Route::get('noticiasSoloImagen/{pag?}',[NoticiaController::class, 'mostrarNoticiasSoloImagen'])->name('solo-imagen');
Route::get('noticiasAutor/{autor}/{pag?}',[NoticiaController::class, 'porAutor'])->name('con-autor');
Route::get('noticiasCarrera/{carrera}/{pag?}',[NoticiaController::class, 'porCarrera'])->name('carrera');
Route::get('noticiasCategoria/{categoria}/{pag?}',[NoticiaController::class, 'porCategoria'])->name('categoria');

resources/views/cargarnoticias.blade.php
@extends('main');

@section('titulo','Crear Noticia')
@section('contenido')

<div class="row"> 
    <div class="col col-md-12">
        <div class="card bg-info  border border-dark m-5 ">
            <div class="card-header text-center">
              <h1 class="card-title text-dark">Cargar una nueva Noticia</h1>
            </div>
            <div class="card-body">
              @if(Session::has('status'))
              <div class="alert alert-success">
                {{Session('status')}}
              </div>
              @endif

              {{Form::open(['route'=>'noticias.store','files'=>true])}}
                @csrf 
              <div class="form-group">
                @error('titulo')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror 
                <em><strong>{{Form::label("Titulo",null,['class'=>'control-label card-text text-dark','for'=>'titulo'])}}</em></strong>
                {{Form::text("titulo",old("titulo"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Título'])}}
              </div>

              <div class="form-group">
                @error('contenido')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Contenido",null,['class'=>'control-label card-text text-dark','for'=>'contenido'])}}</em></strong>
                {{Form::text("contenido",old("contenido"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Contenido'])}}
              </div>  

              <div class="form-group">
                @error('autor')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Autor",null,['class'=>'control-label card-text text-dark','for'=>'autor'])}}</em></strong>
                {{Form::select("autor",$user,null,['class'=>'form-control card-text','placeholder'=>'Seleccione un Autor'])}}
              </div>

              <div class="form-group">
                @error('carrera_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Carrera",null,['class'=>'control-label card-text text-dark','for'=>'carrera_id'])}}</em></strong>
                {{Form::select("carrera_id",$carrera,null,['class'=>'form-control card-text','placeholder'=>'Seleccione una Carrera'])}}
              </div>

              <div class="form-group">
                @error('categoria_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Categoria",null,['class'=>'control-label card-text text-dark','for'=>'categoria_id'])}}</em></strong>
                {{Form::select("categoria_id",$categoria,null,['class'=>'form-control card-text','placeholder'=>'Seleccione una Categoria'])}}
              </div>

              <div class="form-group">
                @error('imagen')
                <div class="alert alert-danger">{{$message}}
                @enderror
                </div> 
                <em><strong>{{Form::label("Imagen",null,['class'=>'control-label card-img text-dark','for'=>'imagen'])}}</em></strong>
                {{Form::file("imagen")}}
              </div>
            <div class="card-footer">
              <button class="btn btn-danger text-dark" type="submit" style="width:100%;"><strong>Guardar</strong></button>
            </div>
              
              {!!Form::close()!!}
            
        </div>
    </div>
</div>

@endsection

resources/views/crearnoticiasimagen.blade.php
@extends('main');

@section('titulo','Noticias')
@section('contenido')

@forelse($contenidoNoticias as $noticia)

@if($loop->iteration % 2!=0)
<div class="row"> 
@endif

    <div class="col col-md-6">
        <div class="card bg-info text-center border border-dark m-5 ">
            @if(isset($noticia->imagen))
            @if(Str::startsWith($noticia->imagen, 'http'))
              <img src="{{ $noticia->imagen }}" class="card-img-top" alt="...">
            @else
              <img src="{{ asset('./storage/'. $noticia->imagen) }}" class="card-img-top" alt="...">  
            @endif
         @else
          <h5 class="text-center text-muted"> No hay imagen disponible </h5>
          <hr>
         @endif
            <div class="card-body">
                <h2 class="card-title pb-2 text-dark"><em>{{$noticia->titulo}}</em></h2>
                <a href="{{route('con-autor',['autor'=>$noticia->creadaPor->id])}}"><p class="card-text pb-2 text-white"><small>{{$noticia->creadaPor->name}}</small></p></a>
                <p class="card-text pb-2 text-white">{!! $noticia->contenido !!}</p>
                <a href="{{route('carrera',['carrera'=>$noticia->perteneceA->id])}}"><span class="badge badge-danger">{{$noticia->perteneceA->nombre}}</span></a>
                <a href="{{route('categoria',['categoria'=>$noticia->categorizada->id])}}"><span class="badge badge-warning">{{$noticia->categorizada->nombre}}</span></a>
            
                
            </div>
            <div class="card-footer text-center">
                <div class="row">
                    <div>
                    <a href="{{route('noticias.show',['noticia'=>$noticia->id])}}" class=" btn btn-success"><img src="https://www.svgrepo.com/show/38604/eye.svg" 
                    width="20" height="20" alt="Mostrar" title="Mostrar"></a>
</div>
                    <div>

                    <a href="{{route('noticias.edit',['noticia'=>$noticia->id])}}" class=" btn btn-warning"><img src="https://www.svgrepo.com/show/6308/pen.svg" 
                    width="20" height="20" alt="Editar" title="Editar"></a>
</div>
                    <div>

                    {{Form::model($noticia,['method'=>'delete','route'=>['noticias.destroy',$noticia->id]])}}
                    @csrf
                    
                    <button type="submit" class="btn btn-danger" onclick="if (!confirm('Está seguro de borrar la noticia?')) return false;"><img src="https://www.svgrepo.com/show/80902/trash.svg" width="20" height="20" alt="Borrar" 
                    title="Borrar"></button>
                    {!!Form::close()!!}
</div>

                </div>
            </div>

        </div>
        </div>

@if($loop->iteration % 2==0)
</div><hr>
@endif

@if($loop->last && $loop->iteration % 2!=0)
</div> <hr>
@endif

@empty 
<div class="alert alert-danger alert-dismissible" role="aler">No hay noticias para mostrar<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>

@endforelse

<div class="d-flex justify-content-center">
{!! $contenidoNoticias->links() !!}
</div>

@endsection

resources/views/main.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <title>@yield('titulo')</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body class="bg-dark">

  <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-info text-white ">
        <div class="container-fluid">
            <div class="navbar-header">
                <img src="../descarga.jpg" alt="image" width="30px" class="img-thumnbnail"> ISFT 38
            </div>
            <div class="collapse navbar-collapse ">
                <ul class="navbar-nav  ">
                    <li class="nav-item  text-primary"><a class="nav-link" href="{{route('noticias.index')}}">Noticias</a></li>
                    <li class="nav-item text-primary"><a class="nav-link" href="{{route('solo-imagen')}}">Con Imágen</a></li>
                    <li class="nav-item text-primary"><a class="nav-link" href="{{route('noticias.create')}}">Crear Noticias</a></li>
                </ul>
            </div>
        </div>
    </nav>
<br>
<div class="container-fluid bg-dark">
        <div class="row">
            <div class="col col-md-12">
           
@yield('contenido')

</div>
</div>
</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    </body>
</html>

resources/views/modificarnoticias.blade.php
@extends('main');

@section('titulo','Modificar Noticia')
@section('contenido')

<div class="row"> 
    <div class="col col-md-12">
        <div class="card bg-info  border border-dark m-5 ">
            <div class="card-header text-center">
              <h1 class="card-title text-dark">Modificar Noticia: "{{$noticia->titulo}}"</h1>
            </div>
            <div class="card-body">
              @if(Session::has('status'))
              <div class="alert alert-success">
                {{Session('status')}}
              </div>
              @endif

              {{Form::model($noticia,['method'=>'put','route'=>['noticias.update',$noticia->id],'files'=>true])}}
                @csrf 
              <div class="form-group">
                @error('titulo')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror 
                <em><strong>{{Form::label("Titulo",null,['class'=>'control-label card-text text-dark','for'=>'titulo'])}}</em></strong>
                {{Form::text("titulo",old("titulo"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Título'])}}
              </div>

              <div class="form-group">
                @error('contenido')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Contenido",null,['class'=>'control-label card-text text-dark','for'=>'contenido'])}}</em></strong>
                {{Form::text("contenido",old("contenido"),['class'=>'form-control card-text','placeholder'=>'Ingrese el Contenido'])}}
              </div>  

              <div class="form-group">
                @error('autor')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Autor",null,['class'=>'control-label card-text text-dark','for'=>'autor'])}}</em></strong>
                {{Form::select("autor",$usuario,null,['class'=>'form-control card-text','placeholder'=>'Seleccione un Autor'])}}
              </div>

              <div class="form-group">
                @error('carrera_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Carrera",null,['class'=>'control-label card-text text-dark','for'=>'carrera_id'])}}</em></strong>
                {{Form::select("carrera_id",$carrera,null,['class'=>'form-control card-text','placeholder'=>'Seleccione una Carrera'])}}
              </div>

              <div class="form-group">
                @error('categoria_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Categoria",null,['class'=>'control-label card-text text-dark','for'=>'categoria_id'])}}</em></strong>
                {{Form::select("categoria_id",$categoria,null,['class'=>'form-control card-text','placeholder'=>'Seleccione una Categoria'])}}
              </div>


              <div class="form-group">
                @error('imagen')
                <div class="alert alert-danger">{{$message}}
                @enderror
                </div> 
                <em><strong>{{Form::label("Imagen",null,['class'=>'control-label card-img text-dark','for'=>'imagen'])}}</em></strong>
                @if($noticia->imagen)
                    @if(Str::startsWith($noticia->imagen,'http'))
                        <img src="{{$noticia->imagen}}" class="img-responsive" alt="..." width="300">
                    @else
                        <img src="{{asset('./storage/'.$noticia->imagen)}}" class="img-responsive" width="300"  alt="...">   
                        @endif
               
                @endif 
                {{Form::file("imagen")}}
              </div>
            <div class="card-footer">
              <button class="btn btn-danger text-dark" type="submit" style="width:100%;"><strong>Guardar</strong></button>
            </div>
              
              {!!Form::close()!!}
            
        </div>
    </div>
</div>

@endsection

resources/views/mostrar1noticia.blade.php
@extends('main');

@section('titulo','Modificar Noticia')
@section('contenido')

<div class="row"> 
    <div class="col col-md-12">
        <div class="card bg-info  border border-dark m-5 ">
            <div class="card-header text-center">
              <h1 class="card-title text-dark">Modificar Noticia: "{{$noticia->titulo}}"</h1>
            </div>
            <div class="card-body">
              @if(Session::has('status'))
              <div class="alert alert-success">
                {{Session('status')}}
              </div>
              @endif

              {{Form::model($noticia,['method'=>'get','route'=>['noticias.show',$noticia->id]])}}
                @csrf 
              <div class="form-group">
                @error('titulo')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror 
                <em><strong>{{Form::label("Titulo",null,['class'=>'control-label card-text text-dark','for'=>'titulo'])}}</em></strong>
                {{Form::text("titulo",old("titulo"),['class'=>'form-control card-text','readonly'])}}
              </div>

              <div class="form-group">
                @error('contenido')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Contenido",null,['class'=>'control-label card-text text-dark','for'=>'contenido'])}}</em></strong>
                {{Form::text("contenido",old("contenido"),['class'=>'form-control card-text','readonly'])}}
              </div>  

              <div class="form-group">
                @error('autor')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Autor",null,['class'=>'control-label card-text text-dark','for'=>'autor'])}}</em></strong>
                {{Form::select("autor",$usuario,null,['class'=>'form-control card-text','disabled','readonly'])}}
              </div>

              <div class="form-group">
                @error('carrera_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Carrera",null,['class'=>'control-label card-text text-dark','for'=>'carrera_id'])}}</em></strong>
                {{Form::select("carrera_id",$carrera,null,['class'=>'form-control card-text','disabled','readonly'])}}
              </div>

              <div class="form-group">
                @error('categoria_id')
                <div class="alert alert-danger">{{$message}}</div> 
                @enderror
                <em><strong>{{Form::label("Categoria",null,['class'=>'control-label card-text text-dark','for'=>'categoria_id'])}}</em></strong>
                {{Form::select("categoria_id",$categoria,null,['class'=>'form-control card-text','disabled','readonly'])}}
              </div>

              <div class="form-group">
                @error('imagen')
                <div class="alert alert-danger">{{$message}}
                @enderror
                </div> 
                <em><strong>{{Form::label("Imagen",null,['class'=>'control-label card-img text-dark','for'=>'imagen'])}}</em></strong>
                @if($noticia->imagen)
                    @if(Str::startsWith($noticia->imagen,'http'))
                        <img src="{{$noticia->imagen}}" class="img-responsive" alt="...">
                    @else
                        <img src="{{asset('./storage/'.$noticia->imagen)}}" class="img-responsive" alt="...">   
                        @endif
                @else
                    <h5 class="text-center text-muted">No hay imagen para mostrar</h5><hr>
                @endif    
              </div>
              {!!Form::close()!!}
            
        </div>
    </div>
</div>

@endsection